language: rust
sudo: false

rust:
- 1.8.0
- stable
- beta
- nightly

before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH

script:
- travis-cargo build
- travis-cargo test
- travis-cargo doc -- --no-deps
- (cd benchmark && travis-cargo build)
- benchmark/target/debug/mutex 2 1 0 1
- benchmark/target/debug/rwlock 1 1 1 0 1

after_success:
- travis-cargo --only nightly doc-upload

env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly

notifications:
  email: false
