[package]
name = "parking_lot"
version = "0.3.3"
authors = ["Amanieu d'Antras <amanieu@gmail.com>"]
description = "More compact and efficient implementations of the standard synchronization primitives."
documentation = "https://amanieu.github.io/parking_lot/parking_lot/index.html"
license = "Apache-2.0/MIT"
repository = "https://github.com/Amanieu/parking_lot"
readme = "README.md"
keywords = ["mutex", "condvar", "rwlock", "once", "thread"]

[dependencies]
parking_lot_core = { path = "core", version = "0.1" }
owning_ref = "0.2"

[dev-dependencies]
rand = "0.3"

[features]
nightly = ["parking_lot_core/nightly"]
