[package]
name = "parking_lot"
version = "0.8.0"
authors = ["Amanieu d'Antras <amanieu@gmail.com>"]
description = "More compact and efficient implementations of the standard synchronization primitives."
license = "Apache-2.0/MIT"
repository = "https://github.com/Amanieu/parking_lot"
readme = "README.md"
keywords = ["mutex", "condvar", "rwlock", "once", "thread"]
categories = ["concurrency"]
edition = "2018"

[dependencies]
parking_lot_core = { path = "core", version = "0.5" }
lock_api = { path = "lock_api", version = "0.2" }

# Optional dependency for supporting serde.  Use the feature "enable_serde" to
# get access to this.
serde = {version = "1.0.90", features = ["derive", "rc", "std"], optional = true}

[dev-dependencies]
rand = "0.6"
lazy_static = "1.0"

# Used when testing out serde support.
bincode = {version = "1.1.3"}

[build-dependencies]
rustc_version = "0.2"

[features]
default = []
owning_ref = ["lock_api/owning_ref"]
nightly = ["parking_lot_core/nightly", "lock_api/nightly"]
deadlock_detection = ["parking_lot_core/deadlock_detection"]
enable_serde = ["serde", "lock_api/enable_serde"]

[workspace]
exclude = ["benchmark"]
